---
abstract: 'Generate Indonesian monthly HTML calendar'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RSS-From-Forum-vBulletin
requires:
  Exporter::Lite: 0
  LWP::UserAgent: 0
  Mojo::DOM: 0
  Test::More: 0.96
  URI::URL: 0
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/RSS-From-Forum-vBulletin/
  repository: http://github.com/sharyanto/perl-RSS-From-Forum-vBulletin
version: 0.02
